# fly.toml app configuration file generated for young-tree-6265 on 2023-10-22T12:56:29+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-tree-6265"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
