name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54

    - name: Lint Backend
      run: |
        cd ${{ github.workspace }}/backend
        go get -u golang.org/x/lint/golint
        golangci-lint run ./...
      working-directory: ${{ github.workspace }}/backend

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Lint Frontend
      run: |
        cd ${{ github.workspace }}/frontend
        npm install
        npm run lint
      working-directory: ${{ github.workspace }}/frontend
