name: Lint Code Base

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Backend Code
        run: |
          cd ${{ github.workspace }}/backend/
          # Assuming you have a Go linter like golangci-lint
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          golangci-lint run
          # Add any additional Go linting commands here

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Lint Frontend Code
        run: |
          cd ${{ github.workspace }}/frontend/
          npm install
          npm run lint
          # Add any additional frontend linting commands here
