name: Lint Code Base

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.10 # Specify the Go version you need

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.0
          golangci-lint --version

      - name: Lint Backend Code
        run: |
          cd ${{ github.workspace }}/backend/
          golangci-lint run
          # Add any additional Go linting commands here

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Lint Frontend Code
        run: |
          cd ${{ github.workspace }}/frontend/
          npm install
          npm run lint
          # Add any additional frontend linting commands here
